// Test scenarios: license settings + courses + what the dashboard should show, worked out by hand from the
// board's rules (not from the app). Used by scripts/test-scenarios.ts and the dev-only "Load test scenario" option.
// Dates assume "today" is between Oct 1, 2026 and Jan 31, 2027.

export type ScenarioCourse = { title: string; provider: string; date: string; hours: number; field: string; delivery?: string };
// A dashboard line and what it should read. `y` = the year box (sub-period index), omitted for whole-cycle lines.
export type Expect = { id: string; y?: number; earned: number; required: number; remaining?: number; met?: boolean; past?: boolean; over?: number; absent?: boolean; coveredBy?: string;
  alt?: { area: string; earned: number; remaining: number }; // NY: the 24-in-one-subject option shown beside the 40
  warn?: string }; // text the red warning under the line must contain (ID: total can no longer be reached)
export type Scenario = {
  id: string; state: string; title: string; checks: string;
  license: { expiration: string; issued?: string; practice?: string[]; firstRenewal?: boolean; regulatoryReviewDue?: string };
  courses: ScenarioCourse[];
  expect: Expect[];
  stillNeeded?: { total: number; rows: string[] }; // "Group: Label hours", e.g. "Year 2: Technical 12"
};

const P = "Test Provider";

export const SCENARIOS: Scenario[] = [
  {
    id: "CA-1", state: "CA", title: "Clean slate",
    checks: "Every requirement shows 0 and the full amount to go; the summary splits 80 hours correctly (the 4 ethics hours are part of the 40 technical); nothing is past due.",
    license: { expiration: "2028-01-31", issued: "2016-03-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 80, remaining: 80 },
      { id: "annual_total", y: 1, earned: 0, required: 20, remaining: 20 },
      { id: "annual_total", y: 2, earned: 0, required: 20, remaining: 20 },
      { id: "technical_total", earned: 0, required: 40, remaining: 40 },
      { id: "technical_annual", y: 1, earned: 0, required: 12, remaining: 12 },
      { id: "technical_annual", y: 2, earned: 0, required: 12, remaining: 12 },
      { id: "non_technical_max", earned: 0, required: 40 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "aa", earned: 0, required: 0, absent: true },
      { id: "fraud", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 80, rows: ["Year 1: Technical 12", "Year 1: Any subject 8", "Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Technical 12", "Any time: Ethics 4", "Any time: Any subject 24"] },
  },
  {
    id: "CA-2", state: "CA", title: "Typical first year, two kinds of ethics",
    checks: "A Regulatory Ethics course counts as technical and toward the 4 ethics hours; a Behavioral Ethics course is non-technical in California and doesn't count toward ethics (CBA renewal overview, p. 3). Software and personal development are non-technical.",
    license: { expiration: "2028-01-31", issued: "2016-03-01" },
    courses: [
      { title: "Individual Tax Update", provider: P, date: "2026-03-10", hours: 8, field: "Taxes" },
      { title: "Leading Hybrid Teams", provider: P, date: "2026-04-15", hours: 6, field: "Personal Development" },
      { title: "Ethics for CPAs", provider: P, date: "2026-05-20", hours: 4, field: "Regulatory Ethics" },
      { title: "Excel Power Query", provider: P, date: "2026-06-05", hours: 3, field: "Computer Software and Applications" },
      { title: "Ethical Decision-Making at Work", provider: P, date: "2026-07-08", hours: 2, field: "Behavioral Ethics" },
    ],
    expect: [
      { id: "total", earned: 23, required: 80, remaining: 57 },
      { id: "annual_total", y: 1, earned: 23, required: 20, met: true },
      { id: "technical_annual", y: 1, earned: 12, required: 12, met: true },
      { id: "technical_total", earned: 12, required: 40, remaining: 28 },
      { id: "non_technical_max", earned: 11, required: 40 },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 57, rows: ["Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Technical 16", "Any time: Any subject 21"] },
  },
  {
    id: "CA-3", state: "CA", title: "All 40 technical hours in Year 1",
    checks: "Year 2 still needs its own 12 technical, so only 28 of the 40 technical hours count toward the 40 for now.",
    license: { expiration: "2028-01-31", issued: "2016-03-01" },
    courses: [
      { title: "Revenue Recognition Deep Dive", provider: P, date: "2026-03-02", hours: 30, field: "Accounting" },
      { title: "Audit Sampling", provider: P, date: "2026-04-02", hours: 10, field: "Auditing" },
    ],
    expect: [
      { id: "technical_total", earned: 28, required: 40, remaining: 12 },
      { id: "technical_annual", y: 1, earned: 40, required: 12, met: true },
      { id: "technical_annual", y: 2, earned: 0, required: 12, remaining: 12 },
      { id: "total", earned: 40, required: 80, remaining: 40 },
    ],
    stillNeeded: { total: 40, rows: ["Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Ethics 4", "Any time: Any subject 16"] },
  },
  {
    id: "CA-4", state: "CA", title: "Too much non-technical",
    checks: "Only 40 non-technical hours can count (50% of 80); the 5 extra don't count toward the 80. With the non-technical allowance used up, everything still needed must be technical — 28 hours, not 40.",
    license: { expiration: "2028-01-31", issued: "2016-03-01" },
    courses: [
      { title: "Personal Brand Bootcamp", provider: P, date: "2026-03-05", hours: 30, field: "Personal Development" },
      { title: "Presentation Skills", provider: P, date: "2026-04-05", hours: 15, field: "Communications and Marketing" },
      { title: "Corporate Tax Update", provider: P, date: "2026-05-05", hours: 12, field: "Taxes" },
    ],
    expect: [
      { id: "non_technical_max", earned: 45, required: 40, over: 5 },
      { id: "total", earned: 52, required: 80, remaining: 28 },
      { id: "technical_total", earned: 12, required: 40, remaining: 28 },
    ],
    stillNeeded: { total: 28, rows: ["Year 2: Technical 20", "Any time: Technical 4", "Any time: Ethics 4"] },
  },
  {
    id: "CA-5", state: "CA", title: "Year 1 already ended short",
    checks: "A year that has ended short shows red 'hrs short — was due by…', isn't the next deadline, and drops out of 'What you still need'.",
    license: { expiration: "2027-05-31", issued: "2016-03-01" },
    courses: [
      { title: "Tax Planning Strategies", provider: P, date: "2025-09-15", hours: 8, field: "Taxes" },
      { title: "Time Management", provider: P, date: "2025-11-01", hours: 10, field: "Personal Development" },
      { title: "Audit Update", provider: P, date: "2026-07-01", hours: 6, field: "Auditing" },
    ],
    expect: [
      { id: "annual_total", y: 1, earned: 18, required: 20, remaining: 2, past: true },
      { id: "technical_annual", y: 1, earned: 8, required: 12, remaining: 4, past: true },
      { id: "annual_total", y: 2, earned: 6, required: 20, remaining: 14 },
      { id: "technical_annual", y: 2, earned: 6, required: 12, remaining: 6 },
      { id: "technical_total", earned: 14, required: 40, remaining: 26 },
      { id: "total", earned: 24, required: 80, remaining: 56 },
    ],
    stillNeeded: { total: 56, rows: ["Year 2: Technical 6", "Year 2: Any subject 8", "Any time: Technical 16", "Any time: Ethics 4", "Any time: Any subject 22"] },
  },
  {
    id: "CA-6", state: "CA", title: "Audit/attest work with a fraud course",
    checks: "A&A needs 24 hours PLUS 4 fraud: the fraud course counts as technical and toward fraud, but not toward the 24 A&A. A governmental accounting course does count toward A&A (meeting the government requirement is deemed to meet A&A).",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["attest"] },
    courses: [
      { title: "Audit Sampling", provider: P, date: "2026-03-10", hours: 8, field: "Auditing" },
      { title: "Revenue Recognition", provider: P, date: "2026-04-10", hours: 10, field: "Accounting" },
      { title: "Fraud Risk in Financial Statement Audits", provider: P, date: "2026-05-10", hours: 4, field: "Auditing" },
      { title: "GASB Update", provider: P, date: "2026-06-10", hours: 2, field: "Accounting (Governmental)" },
    ],
    expect: [
      { id: "aa", earned: 20, required: 24, remaining: 4 },
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "technical_total", earned: 24, required: 40, remaining: 16 },
      { id: "total", earned: 24, required: 80, remaining: 56 },
      { id: "gov", earned: 0, required: 0, absent: true },
      { id: "prep", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 56, rows: ["Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Ethics 4", "Any time: Accounting & auditing 4", "Any time: Any subject 28"] },
  },
  {
    id: "CA-7", state: "CA", title: "Government audits cover A&A and prep",
    checks: "With A&A, government and preparation engagements all selected, only Government 24 + Fraud 4 apply (CBA: meeting government + fraud is deemed to meet A&A; either covers prep).",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["attest", "government_audit", "preparation_engagement"] },
    courses: [
      { title: "GASB Update", provider: P, date: "2026-03-12", hours: 6, field: "Accounting (Governmental)" },
      { title: "Single Audit Essentials", provider: P, date: "2026-04-12", hours: 8, field: "Auditing (Governmental)" },
    ],
    expect: [
      { id: "gov", earned: 14, required: 24, remaining: 10 },
      { id: "fraud", earned: 0, required: 4, remaining: 4 },
      { id: "aa", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "prep", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "technical_total", earned: 14, required: 40, remaining: 26 },
    ],
  },
  {
    id: "CA-8", state: "CA", title: "New licensee, first renewal (2 full six-month periods)",
    checks: "Licensed 8/15/2025, first expiration 1/31/2027: two full six-month periods → 40 hours, half technical, 2-hr Regulatory Review, no ethics, no yearly minimums. Courses before the issue date don't count.",
    license: { expiration: "2027-01-31", issued: "2025-08-15", firstRenewal: true },
    courses: [
      { title: "CPA Exam Review – FAR", provider: P, date: "2025-06-01", hours: 8, field: "Taxes" },
      { title: "Payroll Tax Basics", provider: P, date: "2025-10-01", hours: 10, field: "Taxes" },
      { title: "Career Growth Summit", provider: P, date: "2026-03-01", hours: 25, field: "Personal Development" },
      { title: "Regulatory Review for California CPAs", provider: P, date: "2026-05-01", hours: 2, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 32, required: 40, remaining: 8 },
      { id: "technical_total", earned: 12, required: 20, remaining: 8 },
      { id: "non_technical_max", earned: 25, required: 20, over: 5 },
      { id: "regulatory_review", earned: 2, required: 2, met: true },
      { id: "ethics", earned: 0, required: 0, absent: true },
      { id: "annual_total", y: 1, earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 8, rows: ["Any time: Technical 8"] },
  },
  {
    id: "CA-9", state: "CA", title: "New licensee, under six months — Regulatory Review only",
    checks: "Licensed 9/1/2026, first expiration 1/31/2027: no full six-month period, so no CE hours are due — but licensed on or after 7/1/2024, so the 2-hour Regulatory Review course is still required (CBA renewal overview, p. 9).",
    license: { expiration: "2027-01-31", issued: "2026-09-01", firstRenewal: true },
    courses: [],
    expect: [{ id: "total", earned: 0, required: 0, met: true }, { id: "regulatory_review", earned: 0, required: 2, remaining: 2 }],
    stillNeeded: { total: 2, rows: ["Any time: Board-approved Regulatory Review course 2"] },
  },
  {
    id: "CA-10", state: "CA", title: "Regulatory Review due this cycle; not ethics",
    checks: "With a Regulatory Review due date inside the cycle, the 2-hr course is required. It counts as technical but NOT toward the 4 ethics hours (CBA: not interchangeable).",
    license: { expiration: "2028-01-31", issued: "2016-03-01", regulatoryReviewDue: "2027-06-30" },
    courses: [
      { title: "Regulatory Review for California CPAs", provider: P, date: "2026-08-01", hours: 2, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "regulatory_review", earned: 2, required: 2, met: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "technical_total", earned: 2, required: 40, remaining: 38 },
    ],
  },
  {
    id: "CA-11", state: "CA", title: "Duplicates and courses outside the cycle",
    checks: "The same course entered twice counts once (flagged as a duplicate); a course before the cycle and one after it don't count.",
    license: { expiration: "2028-01-31", issued: "2016-03-01" },
    courses: [
      { title: "Lease Accounting Update", provider: P, date: "2026-03-01", hours: 8, field: "Accounting" },
      { title: "Lease Accounting Update", provider: P, date: "2026-03-01", hours: 8, field: "Accounting" },
      { title: "Old Tax Course", provider: P, date: "2025-12-15", hours: 5, field: "Taxes" },
      { title: "Future Audit Course", provider: P, date: "2028-03-01", hours: 5, field: "Auditing" },
    ],
    expect: [
      { id: "total", earned: 8, required: 80, remaining: 72 },
      { id: "technical_annual", y: 1, earned: 8, required: 12, remaining: 4 },
    ],
  },
  {
    id: "CA-12", state: "CA", title: "Regulatory Review estimated from the issue date",
    checks: "No Regulatory Review date entered, licensed 6/1/2015: the estimate rolls forward every six years (2021 → 6/1/2027), so it's due this cycle — shown as 'to go', never overdue.",
    license: { expiration: "2028-01-31", issued: "2015-06-01" },
    courses: [],
    expect: [
      { id: "regulatory_review", earned: 0, required: 2, remaining: 2 },
      { id: "technical_total", earned: 0, required: 40, remaining: 40 },
    ],
    stillNeeded: { total: 80, rows: ["Year 1: Technical 12", "Year 1: Any subject 8", "Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Technical 10", "Any time: Ethics 4", "Any time: Board-approved Regulatory Review course 2", "Any time: Any subject 24"] },
  },
  {
    id: "CA-13", state: "CA", title: "A&A, government and prep all at once",
    checks: "With all three practice areas, only Government 24 + Fraud 4 apply. Only governmental courses count toward the 24 — regular audit and prep courses don't, even though they're A&A. Fraud courses count only toward fraud. Everything counts as technical.",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["attest", "government_audit", "preparation_engagement"] },
    courses: [
      { title: "Audit Sampling", provider: P, date: "2026-03-03", hours: 10, field: "Auditing" },
      { title: "Single Audit Essentials", provider: P, date: "2026-04-07", hours: 8, field: "Auditing (Governmental)" },
      { title: "GASB Update", provider: P, date: "2026-05-05", hours: 6, field: "Accounting (Governmental)" },
      { title: "Preparation Engagements under SSARS 21", provider: P, date: "2026-06-09", hours: 4, field: "Accounting" },
      { title: "Fraud in Governmental Audits", provider: P, date: "2026-07-14", hours: 2, field: "Auditing (Governmental)" },
      { title: "Fraud Risk Assessment", provider: P, date: "2026-08-11", hours: 2, field: "Auditing" },
    ],
    expect: [
      { id: "gov", earned: 14, required: 24, remaining: 10 },
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "aa", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "prep", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "technical_total", earned: 28, required: 40, remaining: 12 }, // 32 logged; Year 2 still owes 12
      { id: "technical_annual", y: 1, earned: 32, required: 12, met: true },
      { id: "total", earned: 32, required: 80, remaining: 48 },
    ],
    stillNeeded: { total: 48, rows: ["Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Ethics 4", "Any time: Governmental accounting & auditing 10", "Any time: Any subject 14"] },
  },
  {
    id: "CA-14", state: "CA", title: "A&A and prep (no government)",
    checks: "A&A 24 + Fraud 4 apply and A&A covers prep, so there's no prep line. Compilation/prep and governmental courses count toward the 24; the fraud course doesn't.",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["attest", "preparation_engagement"] },
    courses: [
      { title: "Audit Sampling", provider: P, date: "2026-03-03", hours: 10, field: "Auditing" },
      { title: "Compilations and Reviews Update", provider: P, date: "2026-04-07", hours: 6, field: "Accounting" },
      { title: "GASB Update", provider: P, date: "2026-05-05", hours: 4, field: "Accounting (Governmental)" },
      { title: "Fraud Risk Assessment", provider: P, date: "2026-06-09", hours: 4, field: "Auditing" },
    ],
    expect: [
      { id: "aa", earned: 20, required: 24, remaining: 4 },
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "prep", earned: 0, required: 0, coveredBy: "Accounting & auditing" },
      { id: "gov", earned: 0, required: 0, absent: true },
      { id: "technical_total", earned: 24, required: 40, remaining: 16 },
    ],
    stillNeeded: { total: 56, rows: ["Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Ethics 4", "Any time: Accounting & auditing 4", "Any time: Any subject 28"] },
  },
  {
    id: "CA-15", state: "CA", title: "Preparation engagements only",
    checks: "Prep alone: 8 hours of prep/A&A subject matter + 4 fraud, and the fraud course doesn't count toward the 8 (CBA: together they make 12 technical hours).",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["preparation_engagement"] },
    courses: [
      { title: "Preparation Engagements under SSARS 21", provider: P, date: "2026-03-10", hours: 6, field: "Accounting" },
      { title: "Fraud Awareness for Accountants", provider: P, date: "2026-04-14", hours: 4, field: "Auditing" },
    ],
    expect: [
      { id: "prep", earned: 6, required: 8, remaining: 2 },
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "aa", earned: 0, required: 0, absent: true },
      { id: "gov", earned: 0, required: 0, absent: true },
      { id: "technical_total", earned: 10, required: 40, remaining: 30 },
    ],
  },
  {
    id: "CA-16", state: "CA", title: "New licensee with all three practice areas",
    checks: "First renewal with 40 hours required (two full six-month periods): government scales to 6 per 20 = 12 and covers A&A and prep; fraud and ethics apply only when the full 80 is required, so neither shows.",
    license: { expiration: "2027-01-31", issued: "2025-08-15", firstRenewal: true, practice: ["attest", "government_audit", "preparation_engagement"] },
    courses: [
      { title: "Single Audit Essentials", provider: P, date: "2025-11-04", hours: 8, field: "Auditing (Governmental)" },
      { title: "Audit Sampling", provider: P, date: "2026-02-10", hours: 6, field: "Auditing" },
      { title: "Regulatory Review for California CPAs", provider: P, date: "2026-03-17", hours: 2, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 16, required: 40, remaining: 24 },
      { id: "gov", earned: 8, required: 12, remaining: 4 },
      { id: "aa", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "prep", earned: 0, required: 0, coveredBy: "Governmental accounting & auditing" },
      { id: "fraud", earned: 0, required: 0, absent: true },
      { id: "ethics", earned: 0, required: 0, absent: true },
      { id: "technical_total", earned: 16, required: 20, remaining: 4 },
      { id: "regulatory_review", earned: 2, required: 2, met: true },
    ],
  },
  {
    id: "CA-17", state: "CA", title: "More than 4 fraud hours, government audits",
    checks: "The first 4 fraud hours (earliest courses first) count only toward Fraud; the 3 extra hours from the governmental fraud course also count toward the 24 government hours.",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["government_audit"] },
    courses: [
      { title: "Fraud Risk Assessment", provider: P, date: "2026-03-03", hours: 3, field: "Auditing" },
      { title: "Fraud in Governmental Audits", provider: P, date: "2026-04-07", hours: 4, field: "Auditing (Governmental)" },
      { title: "GASB Update", provider: P, date: "2026-05-05", hours: 8, field: "Accounting (Governmental)" },
    ],
    expect: [
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "gov", earned: 11, required: 24, remaining: 13 },
      { id: "technical_total", earned: 15, required: 40, remaining: 25 },
      { id: "total", earned: 15, required: 80, remaining: 65 },
      { id: "annual_total", y: 1, earned: 15, required: 20, remaining: 5 },
    ],
    stillNeeded: { total: 65, rows: ["Year 1: Any subject 5", "Year 2: Technical 12", "Year 2: Any subject 8", "Any time: Ethics 4", "Any time: Governmental accounting & auditing 13", "Any time: Any subject 23"] },
  },
  {
    id: "CA-18", state: "CA", title: "More than 4 fraud hours, A&A",
    checks: "One 6-hour fraud audit course: 4 hours go to Fraud, the other 2 also count toward the 24 A&A hours.",
    license: { expiration: "2028-01-31", issued: "2016-03-01", practice: ["attest"] },
    courses: [
      { title: "Fraud in Financial Statement Audits", provider: P, date: "2026-03-03", hours: 6, field: "Auditing" },
      { title: "Audit Sampling", provider: P, date: "2026-04-07", hours: 10, field: "Auditing" },
    ],
    expect: [
      { id: "fraud", earned: 4, required: 4, met: true },
      { id: "aa", earned: 12, required: 24, remaining: 12 },
      { id: "technical_total", earned: 16, required: 40, remaining: 24 },
    ],
  },
  // ---------- Texas: license renews yearly at the end of the birth month; 120 in the last 36 months, 20 in each
  // reporting year, Board ethics course every two years, non-technical and nano capped at 50% (22 TAC 523).
  // All but the new-licensee ones: renewal 03/31/2027 → look-back Apr 1, 2024 – Mar 31, 2027.
  {
    id: "TX-1", state: "TX", title: "Clean slate",
    checks: "120 hours over three reporting years, 20 in each, at least 60 technical. With no courses the two earlier reporting years show red 'short'; this year and the 120 are still to go; ethics 0 / 4.",
    license: { expiration: "2027-03-31", issued: "2012-06-15" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 120, remaining: 120 },
      { id: "annual_total", y: 9, earned: 0, required: 20, remaining: 20 },
      { id: "annual_total_prior1", y: 8, earned: 0, required: 20, remaining: 20, past: true },
      { id: "annual_total_prior2", y: 7, earned: 0, required: 20, remaining: 20, past: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "technical_total", earned: 0, required: 60, remaining: 60 },
      { id: "non_technical_max", earned: 0, required: 60 },
      { id: "nano_max", earned: 0, required: 60 },
    ],
    stillNeeded: { total: 120, rows: ["This reporting year: Any subject 20", "Any time: Technical 56", "Any time: Board-approved Texas ethics course 4", "Any time: Any subject 40"] },
  },
  {
    id: "TX-2", state: "TX", title: "Typical three years",
    checks: "Each reporting year has its 20; a 'Texas Ethics' course in the last 24 months meets ethics; 104 of 120.",
    license: { expiration: "2027-03-31", issued: "2012-06-15" },
    courses: [
      { title: "Individual Tax Update", provider: P, date: "2024-06-10", hours: 40, field: "Taxes" },
      { title: "Revenue Recognition", provider: P, date: "2025-06-10", hours: 40, field: "Accounting" },
      { title: "Audit Update", provider: P, date: "2026-05-12", hours: 20, field: "Auditing" },
      { title: "Texas Ethics for CPAs", provider: P, date: "2026-06-16", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 104, required: 120, remaining: 16 },
      { id: "annual_total", y: 9, earned: 24, required: 20, met: true },
      { id: "annual_total_prior1", y: 8, earned: 40, required: 20, met: true },
      { id: "annual_total_prior2", y: 7, earned: 40, required: 20, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 16, rows: ["Any time: Any subject 16"] },
  },
  {
    id: "TX-3", state: "TX", title: "Too much non-technical",
    checks: "Only 60 non-technical credits count (§ 523.118(a)), so Technical shows 50 / 60; the 10 extra don't count toward the 120, and what's left must be technical.",
    license: { expiration: "2027-03-31", issued: "2012-06-15" },
    courses: [
      { title: "Leadership Academy", provider: P, date: "2024-09-10", hours: 40, field: "Personal Development" },
      { title: "Communication Skills", provider: P, date: "2025-09-09", hours: 30, field: "Communications and Marketing" },
      { title: "Tax Update", provider: P, date: "2026-06-09", hours: 50, field: "Taxes" },
    ],
    expect: [
      { id: "non_technical_max", earned: 70, required: 60, over: 10 },
      { id: "technical_total", earned: 50, required: 60, remaining: 10 },
      { id: "total", earned: 110, required: 120, remaining: 10 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 10, rows: ["Any time: Technical 6", "Any time: Board-approved Texas ethics course 4"] },
  },
  {
    id: "TX-4", state: "TX", title: "Too much nano-learning",
    checks: "Only 60 nano-learning credits count (§ 523.118(b)), using each course's delivery format; the 5 extra don't count toward the 120.",
    license: { expiration: "2027-03-31", issued: "2012-06-15" },
    courses: [
      { title: "Nano Tax Bites", provider: P, date: "2024-10-01", hours: 30, field: "Taxes", delivery: "Nano Learning" },
      { title: "Nano Audit Bites", provider: P, date: "2025-10-01", hours: 35, field: "Auditing", delivery: "Nano Learning" },
      { title: "Lease Accounting", provider: P, date: "2026-04-14", hours: 20, field: "Accounting", delivery: "Group Live" },
      { title: "Texas Ethics for CPAs", provider: P, date: "2026-06-16", hours: 4, field: "Regulatory Ethics", delivery: "Group Internet Based" },
    ],
    expect: [
      { id: "nano_max", earned: 65, required: 60, over: 5 },
      { id: "total", earned: 84, required: 120, remaining: 36 },
      { id: "annual_total_prior1", y: 8, earned: 35, required: 20, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 36, rows: ["Any time: Any course except Nano Learning 36"] },
  },
  {
    id: "TX-5", state: "TX", title: "Ethics too old or not Board-approved",
    checks: "A Texas ethics course from 26 months ago is outside the 24-month window (but still counts toward the 120); an ethics course without 'Texas' or 'TSBPA' in the title isn't treated as the Board course. An earlier year short shows red.",
    license: { expiration: "2027-03-31", issued: "2012-06-15" },
    courses: [
      { title: "Texas Ethics for CPAs", provider: P, date: "2025-02-04", hours: 4, field: "Regulatory Ethics" },
      { title: "Tax Update", provider: P, date: "2025-05-06", hours: 20, field: "Taxes" },
      { title: "Ethics in Practice", provider: P, date: "2026-02-10", hours: 4, field: "Regulatory Ethics" },
      { title: "Corporate Tax Update", provider: P, date: "2026-05-05", hours: 20, field: "Taxes" },
    ],
    expect: [
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "technical_total", earned: 48, required: 60, remaining: 12 },
      { id: "total", earned: 48, required: 120, remaining: 72 },
      { id: "annual_total_prior2", y: 7, earned: 4, required: 20, remaining: 16, past: true },
      { id: "annual_total_prior1", y: 8, earned: 24, required: 20, met: true },
      { id: "annual_total", y: 9, earned: 20, required: 20, met: true },
    ],
    stillNeeded: { total: 72, rows: ["Any time: Technical 8", "Any time: Board-approved Texas ethics course 4", "Any time: Any subject 60"] },
  },
  {
    id: "TX-6", state: "TX", title: "New licensee, second full license year",
    checks: "Licensed 8/10/2025: the 3/31/2026 renewal started the first full year (nothing due); the 3/31/2027 renewal needs 20 credits in the last 12 months — no 120, no ethics yet, no earlier years shown. Caps are 10 each (half of 20).",
    license: { expiration: "2027-03-31", issued: "2025-08-10" },
    courses: [
      { title: "Tax Basics", provider: P, date: "2026-06-01", hours: 12, field: "Taxes" },
      { title: "Excel for Accountants", provider: P, date: "2026-07-01", hours: 4, field: "Computer Software and Applications" },
    ],
    expect: [
      { id: "annual_total", y: 9, earned: 16, required: 20, remaining: 4 },
      { id: "total", earned: 0, required: 0, absent: true },
      { id: "ethics", earned: 0, required: 0, absent: true },
      { id: "annual_total_prior1", y: 8, earned: 0, required: 0, absent: true },
      { id: "technical_total", earned: 12, required: 10, met: true },
      { id: "non_technical_max", earned: 4, required: 10 },
      { id: "nano_max", earned: 0, required: 10 },
    ],
    stillNeeded: { total: 4, rows: ["This reporting year: Any subject 4"] },
  },
  {
    id: "TX-7", state: "TX", title: "New licensee, third full license year",
    checks: "Licensed 8/10/2024: 60 credits in the last 24 months (Apr 1, 2025 – Mar 31, 2027), 20 in the last 12, and the ethics course starts (two years after the first expiration, 3/31/2025). A course before the 24 months doesn't count.",
    license: { expiration: "2027-03-31", issued: "2024-08-10" },
    courses: [
      { title: "Payroll Taxes", provider: P, date: "2024-12-01", hours: 10, field: "Taxes" },
      { title: "Revenue Recognition", provider: P, date: "2025-06-03", hours: 25, field: "Accounting" },
      { title: "Corporate Tax Update", provider: P, date: "2026-05-05", hours: 15, field: "Taxes" },
      { title: "Texas Ethics for CPAs", provider: P, date: "2026-06-16", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 44, required: 60, remaining: 16 },
      { id: "annual_total", y: 9, earned: 19, required: 20, remaining: 1 },
      { id: "annual_total_prior1", y: 8, earned: 25, required: 20, met: true },
      { id: "annual_total_prior2", y: 7, earned: 0, required: 0, absent: true },
      { id: "ethics", earned: 4, required: 4, met: true },
      { id: "technical_total", earned: 44, required: 30, met: true },
      { id: "non_technical_max", earned: 0, required: 30 },
    ],
    stillNeeded: { total: 16, rows: ["This reporting year: Any subject 1", "Any time: Any subject 15"] },
  },
  {
    id: "TX-8", state: "TX", title: "New licensee, under 12 months",
    checks: "Licensed 5/1/2026, first renewal 3/31/2027: licensed less than 12 months, so no CPE is due (§ 523.112(c)(1)–(2)).",
    license: { expiration: "2027-03-31", issued: "2026-05-01" },
    courses: [],
    expect: [{ id: "total", earned: 0, required: 0, met: true }, { id: "ethics", earned: 0, required: 0, absent: true }],
    stillNeeded: { total: 0, rows: [] },
  },
  // ── New York ── calendar-year CPE (2026), registration through 6/30/2027, licensed 2015. Ethics window 2024–2026.
  {
    id: "NY-1", state: "NY", title: "Clean slate",
    checks: "Annual CPE shows the 40 and the 24-in-one-subject options side by side, both at 0; ethics 0 / 4 for 2024–2026. The 4 ethics count toward either option (NYSED Q&A 2), so the summary says ethics 4 + 20 in any one subject.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 40, remaining: 24, alt: { area: "one subject area", earned: 0, remaining: 24 } },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "attest", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 24, rows: ["Any time: Professional ethics 4", "Any time: Any one subject area 20"] },
  },
  {
    id: "NY-2", state: "NY", title: "24 in taxation plus ethics",
    checks: "20 hours of Taxes + 4 Regulatory Ethics in 2026 meets the 24-hour option (Taxation + 4 ethics) and the ethics requirement. Nothing left to do.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [
      { title: "Individual Tax Update", provider: P, date: "2026-03-10", hours: 12, field: "Taxes" },
      { title: "Partnership Taxation", provider: P, date: "2026-06-15", hours: 8, field: "Taxes" },
      { title: "NY Ethics for CPAs", provider: P, date: "2026-04-10", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 24, required: 40, remaining: 0, met: true, alt: { area: "Taxation", earned: 24, remaining: 0 } },
      { id: "ethics", earned: 4, required: 4, remaining: 0, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "NY-3", state: "NY", title: "40 hours, mixed subjects",
    checks: "12 Accounting + 12 Auditing + 12 Finance (advisory) + 4 ethics = 40 in a mix of areas, so the 40-hour option is met even though no single area reaches 24.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [
      { title: "Revenue Recognition", provider: P, date: "2026-02-01", hours: 12, field: "Accounting" },
      { title: "Audit Sampling", provider: P, date: "2026-03-01", hours: 12, field: "Auditing" },
      { title: "Corporate Finance", provider: P, date: "2026-04-01", hours: 12, field: "Finance" },
      { title: "NY Ethics for CPAs", provider: P, date: "2026-05-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 40, required: 40, remaining: 0, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "NY-4", state: "NY", title: "Behavioral Ethics isn't ethics in NY",
    checks: "Behavioral Ethics counts as Advisory Services in New York, not ethics (NYSED subject descriptions). So ethics stays 0 / 4; with 20 Taxes the 24 option needs 4 more — exactly the 4 ethics hours still owed.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [
      { title: "Ethical Decision Making", provider: P, date: "2026-02-01", hours: 4, field: "Behavioral Ethics" },
      { title: "Tax Planning", provider: P, date: "2026-03-01", hours: 20, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 24, required: 40, remaining: 4, alt: { area: "Taxation", earned: 20, remaining: 4 } },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 4, rows: ["Any time: Professional ethics 4"] },
  },
  {
    id: "NY-5", state: "NY", title: "Ethics taken last year",
    checks: "Ethics from 2025 meets the 4-hour ethics requirement (2024–2026) but counts toward 2025's hours, not 2026's. With 20 Taxes in 2026: 4 more Taxes, or 20 more in any subjects.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [
      { title: "NY Ethics for CPAs", provider: P, date: "2025-06-01", hours: 4, field: "Regulatory Ethics" },
      { title: "Tax Planning", provider: P, date: "2026-03-01", hours: 20, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 20, required: 40, remaining: 4, alt: { area: "Taxation", earned: 20, remaining: 4 } },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 4, rows: ["Any time: Taxation 4"] },
  },
  {
    id: "NY-6", state: "NY", title: "Attest, prior years fell short",
    checks: "Attest work: 16 Auditing (2024) + 14 Accounting (2025) = 30 for 2023–2025 — short of 40, and those years are over, so attest work in 2026 needs 40 in 2026 on its own (6 so far). 2024–2026 has 36, so 4 more this year covers attest work in 2027. Ethics from 2023 is outside 2024–2026.",
    license: { expiration: "2027-06-30", issued: "2015-05-01", practice: ["attest"] },
    courses: [
      { title: "NY Ethics for CPAs", provider: P, date: "2023-05-01", hours: 4, field: "Regulatory Ethics" },
      { title: "Audit Update 2024", provider: P, date: "2024-05-01", hours: 16, field: "Auditing" },
      { title: "GAAP Update 2025", provider: P, date: "2025-05-01", hours: 14, field: "Accounting" },
      { title: "Audit Update 2026", provider: P, date: "2026-05-01", hours: 6, field: "Auditing" },
    ],
    expect: [
      { id: "total", earned: 6, required: 40, remaining: 18, alt: { area: "Auditing", earned: 6, remaining: 18 } },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "attest", earned: 6, required: 40, remaining: 34 },
      { id: "attest_next", earned: 36, required: 40, remaining: 4 },
    ],
    stillNeeded: { total: 38, rows: ["Any time: Professional ethics 4", "Any time: Attest competency for 2026 30", "Any time: Attest competency for 2027 4"] },
  },
  {
    id: "NY-7", state: "NY", title: "Attest, prior years enough",
    checks: "24 Auditing (2024) + 16 Accounting (2025) = 40 for 2023–2025, so attest work in 2026 is covered. For 2027 (2024–2026) there are 40 already. Annual: 20 Auditing in 2026 + 4 ethics = the 24 option met.",
    license: { expiration: "2027-06-30", issued: "2015-05-01", practice: ["attest"] },
    courses: [
      { title: "Audit Update 2024", provider: P, date: "2024-05-01", hours: 24, field: "Auditing" },
      { title: "GAAP Update 2025", provider: P, date: "2025-05-01", hours: 16, field: "Accounting" },
      { title: "Audit Update 2026", provider: P, date: "2026-05-01", hours: 20, field: "Auditing" },
      { title: "NY Ethics for CPAs", provider: P, date: "2026-06-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 24, required: 40, remaining: 0, met: true, alt: { area: "Auditing", earned: 24, remaining: 0 } },
      { id: "ethics", earned: 4, required: 4, met: true },
      { id: "attest", earned: 40, required: 40, met: true },
      { id: "attest_next", earned: 60, required: 40, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "NY-8", state: "NY", title: "New licensee, licensed mid-year",
    checks: "Licensed 3/15/2026: CPE starts on the first January 1 in the first registration period (2027), so nothing is due for 2026. Ethics (2026–2028 for a 2029 renewal) is still shown.",
    license: { expiration: "2029-03-31", issued: "2026-03-15" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 0, met: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 4, rows: ["Any time: Professional ethics 4"] },
  },
  {
    id: "NY-9", state: "NY", title: "No carryover; next year's courses",
    checks: "40 hours in Nov 2025 don't count toward 2026 (no carryforward), and a course dated Jan 2027 counts toward 2027, not 2026. 2026 has only 10 Taxes.",
    license: { expiration: "2027-06-30", issued: "2015-05-01" },
    courses: [
      { title: "Year-end Tax Marathon", provider: P, date: "2025-11-01", hours: 40, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2026-01-05", hours: 10, field: "Taxes" },
      { title: "2027 Tax Update", provider: P, date: "2027-01-10", hours: 8, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 10, required: 40, remaining: 14, alt: { area: "Taxation", earned: 10, remaining: 14 } },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 14, rows: ["Any time: Professional ethics 4", "Any time: Taxation 10"] },
  },
  // ── Idaho ── report due Jan 31, 2027: the two calendar years 2025–2026, 80 hours, 30–50 counted each year, 4 ethics.
  {
    id: "ID-1", state: "ID", title: "Clean slate",
    checks: "2025 has ended with 0, so it shows red 'short'; 2026 needs 30. Only 50 can count for 2026, so 80 can't be reached — the total says so in red, and the summary stops at the 50 that can still count.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 80, remaining: 80, warn: "the most you can reach is 50 of 80" },
      { id: "annual_min", y: 5, earned: 0, required: 30, remaining: 30 },
      { id: "annual_min_2025", y: 4, earned: 0, required: 30, remaining: 30, past: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 50, rows: ["2026: Any subject 30", "Any time: Ethics 4", "Any time: Any subject 16"] },
  },
  {
    id: "ID-2", state: "ID", title: "Typical two years",
    checks: "2025: 45 (with 4 ethics). 2026: 25. Total 70 of 80; 2026 needs 5 more for its 30 and 10 more for the 80.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 41, field: "Taxes" },
      { title: "Ethics for CPAs", provider: P, date: "2025-06-01", hours: 4, field: "Regulatory Ethics" },
      { title: "GAAP Update", provider: P, date: "2026-04-01", hours: 25, field: "Accounting" },
    ],
    expect: [
      { id: "total", earned: 70, required: 80, remaining: 10 },
      { id: "annual_min", y: 5, earned: 25, required: 30, remaining: 5 },
      { id: "annual_min_2025", y: 4, earned: 45, required: 30, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 10, rows: ["2026: Any subject 5", "Any time: Any subject 5"] },
  },
  {
    id: "ID-3", state: "ID", title: "Over 50 in one year; Behavioral Ethics",
    checks: "60 hours in 2025 — only 50 count. 2026: 20 Auditing + 4 Behavioral Ethics (any ethics field of study counts in Idaho). Total 74; 6 more in 2026 finishes both the 30 and the 80.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [
      { title: "Tax Marathon", provider: P, date: "2025-03-01", hours: 60, field: "Taxes" },
      { title: "Audit Update", provider: P, date: "2026-04-01", hours: 20, field: "Auditing" },
      { title: "Ethical Decision Making", provider: P, date: "2026-05-01", hours: 4, field: "Behavioral Ethics" },
    ],
    expect: [
      { id: "total", earned: 74, required: 80, remaining: 6 },
      { id: "annual_min", y: 5, earned: 24, required: 30, remaining: 6 },
      { id: "annual_min_2025", y: 4, earned: 60, required: 30, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 6, rows: ["2026: Any subject 6"] },
  },
  {
    id: "ID-4", state: "ID", title: "All met, ethics split across years",
    checks: "2 Behavioral Ethics in 2025 + 2 Regulatory Ethics in 2026 = 4 ethics over the two years. 42 + 42 = 84 of 80.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 40, field: "Taxes" },
      { title: "Ethics Part 1", provider: P, date: "2025-04-01", hours: 2, field: "Behavioral Ethics" },
      { title: "Audit Update", provider: P, date: "2026-04-01", hours: 40, field: "Auditing" },
      { title: "Ethics Part 2", provider: P, date: "2026-05-01", hours: 2, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 84, required: 80, met: true },
      { id: "annual_min", y: 5, earned: 42, required: 30, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "ID-5", state: "ID", title: "Licensed this year, no Idaho course yet",
    checks: "Licensed 4/15/2026: only the 2-hour Idaho state-specific ethics course is due this year (IDAPA 24.30.01.111). The summary shows just that course.",
    license: { expiration: "2027-01-31", issued: "2026-04-15" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 0, met: true },
      { id: "id_ethics", earned: 0, required: 2, remaining: 2 },
      { id: "annual_min", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 2, rows: ["Any time: Idaho ethics course 2"] },
  },
  {
    id: "ID-6", state: "ID", title: "Licensed last year with the Idaho course",
    checks: "Licensed 4/15/2025 and took the Idaho ethics course that year, so 2025 is credited as 50 (2 ethics + 48). 2026: 28 Taxes + 2 ethics = 30. Total 80; ethics 4.",
    license: { expiration: "2027-01-31", issued: "2025-04-15" },
    courses: [
      { title: "Idaho Ethics for CPAs", provider: P, date: "2025-05-01", hours: 2, field: "Regulatory Ethics" },
      { title: "Tax Update", provider: P, date: "2026-03-01", hours: 28, field: "Taxes" },
      { title: "Ethics for CPAs", provider: P, date: "2026-06-01", hours: 2, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 80, required: 80, met: true },
      { id: "annual_min", y: 5, earned: 30, required: 30, met: true },
      { id: "annual_min_2025", y: 4, earned: 0, required: 0, absent: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "ID-7", state: "ID", title: "Licensed last year without the Idaho course",
    checks: "Licensed 4/15/2025 but no Idaho ethics course in 2025: that shows red, and 2025 isn't credited as 50. With 30 in 2026, only 20 more can count — at most 50 of 80, shown in red.",
    license: { expiration: "2027-01-31", issued: "2025-04-15" },
    courses: [{ title: "Tax Update", provider: P, date: "2026-03-01", hours: 30, field: "Taxes" }],
    expect: [
      { id: "total", earned: 30, required: 80, remaining: 50, warn: "the most you can reach is 50 of 80" },
      { id: "id_ethics", earned: 0, required: 2, remaining: 2, past: true },
      { id: "annual_min", y: 5, earned: 30, required: 30, met: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 20, rows: ["Any time: Ethics 4", "Any time: Any subject 16"] },
  },
  {
    id: "ID-8", state: "ID", title: "Courses outside the two years",
    checks: "2024 (rolled off) and a course dated 1/3/2027 (next window) don't count. 2025: 40; 2026: 30. Total 70; 10 more in 2026.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [
      { title: "Old Tax Course", provider: P, date: "2024-03-01", hours: 50, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 36, field: "Taxes" },
      { title: "Ethics for CPAs", provider: P, date: "2025-04-01", hours: 4, field: "Regulatory Ethics" },
      { title: "Audit Update", provider: P, date: "2026-03-01", hours: 30, field: "Auditing" },
      { title: "New Year Webinar", provider: P, date: "2027-01-03", hours: 10, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 70, required: 80, remaining: 10 },
      { id: "annual_min", y: 5, earned: 30, required: 30, met: true },
      { id: "annual_min_2025", y: 4, earned: 40, required: 30, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 10, rows: ["Any time: Any subject 10"] },
  },
  {
    id: "ID-9", state: "ID", title: "Last year fell short",
    checks: "2025 ended with 20 — red '10 short'. Even 50 in 2026 reaches only 70 of 80, so the total says so in red; the summary lists the 50 that can still count.",
    license: { expiration: "2027-01-31", issued: "2012-05-01" },
    courses: [{ title: "Tax Update", provider: P, date: "2025-03-01", hours: 20, field: "Taxes" }],
    expect: [
      { id: "total", earned: 20, required: 80, remaining: 60, warn: "the most you can reach is 70 of 80" },
      { id: "annual_min_2025", y: 4, earned: 20, required: 30, remaining: 10, past: true },
      { id: "annual_min", y: 5, earned: 0, required: 30, remaining: 30 },
    ],
    stillNeeded: { total: 50, rows: ["2026: Any subject 30", "Any time: Ethics 4", "Any time: Any subject 16"] },
  },
  // ── Washington ── license expires 6/30/2028: CPE period 1/1/2025 – 12/31/2027, 120 hours, 20 each calendar year,
  // at most 60 non-technical (so at least 60 technical), 4-hour Washington Board-approved ethics.
  {
    id: "WA-1", state: "WA", title: "Clean slate",
    checks: "2025 has ended with 0 — red 'short'. 2026 and 2027 need 20 each; 120 total with at least 60 technical (the 4 Washington ethics hours count as technical).",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 120, remaining: 120 },
      { id: "annual_total", y: 1, earned: 0, required: 20, remaining: 20, past: true }, { id: "annual_total", y: 2, earned: 0, required: 20, remaining: 20 }, { id: "annual_total", y: 3, earned: 0, required: 20, remaining: 20 },
      { id: "technical_total", earned: 0, required: 60, remaining: 60 },
      { id: "non_technical_max", earned: 0, required: 60 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 120, rows: ["2026: Any subject 20", "2027: Any subject 20", "Any time: Technical 56", "Any time: Washington Board-approved ethics 4", "Any time: Any subject 20"] },
  },
  {
    id: "WA-2", state: "WA", title: "On track, technical met",
    checks: "2025: 40 Taxes. 2026: 30 Accounting + the 4-hour Washington ethics course. 74 of 120; technical and ethics met; 2027 still needs its 20.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 40, field: "Taxes" },
      { title: "GAAP Update", provider: P, date: "2026-03-01", hours: 30, field: "Accounting" },
      { title: "Washington Ethics and Regulation", provider: P, date: "2026-05-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 74, required: 120, remaining: 46 },
      { id: "annual_total", y: 1, earned: 40, required: 20, met: true }, { id: "annual_total", y: 2, earned: 34, required: 20, met: true }, { id: "annual_total", y: 3, earned: 0, required: 20, remaining: 20 },
      { id: "technical_total", earned: 74, required: 60, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 46, rows: ["2027: Any subject 20", "Any time: Any subject 26"] },
  },
  {
    id: "WA-3", state: "WA", title: "Too much non-technical",
    checks: "70 hours of personal development and communications — only 60 count (10 over). Everything left must be technical: 2027's 20, 36 more any time, and the Washington ethics course.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Leadership Summit", provider: P, date: "2025-03-01", hours: 40, field: "Personal Development" },
      { title: "Business Writing", provider: P, date: "2026-03-01", hours: 30, field: "Communications and Marketing" },
    ],
    expect: [
      { id: "total", earned: 60, required: 120, remaining: 60 },
      { id: "technical_total", earned: 0, required: 60, remaining: 60 },
      { id: "non_technical_max", earned: 70, required: 60, over: 10 },
    ],
    stillNeeded: { total: 60, rows: ["2027: Technical 20", "Any time: Technical 36", "Any time: Washington Board-approved ethics 4"] },
  },
  {
    id: "WA-4", state: "WA", title: "Behavioral Ethics is technical; other ethics isn't the WA course",
    checks: "In Washington all ethics, Behavioral included, is technical (WAC 4-30-132), but only a Washington Board-approved course meets the 4-hour ethics requirement. 54 technical so far; 6 more technical, 4 of them the Washington course.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 30, field: "Taxes" },
      { title: "Tax Planning", provider: P, date: "2026-03-01", hours: 20, field: "Taxes" },
      { title: "AICPA Ethics", provider: P, date: "2026-04-01", hours: 4, field: "Behavioral Ethics" },
    ],
    expect: [
      { id: "total", earned: 54, required: 120, remaining: 66 },
      { id: "technical_total", earned: 54, required: 60, remaining: 6 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 66, rows: ["2027: Any subject 20", "Any time: Technical 2", "Any time: Washington Board-approved ethics 4", "Any time: Any subject 40"] },
  },
  {
    id: "WA-5", state: "WA", title: "Front-loaded hours",
    checks: "120 hours already logged in 2025–2026, but 2027 still owes its own 20, so only 100 count for now. The Washington ethics course taken in 2027 counts toward 2027's 20 — so 20 more hours in 2027 finishes everything.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Tax Marathon", provider: P, date: "2025-03-01", hours: 80, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2026-03-01", hours: 40, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 100, required: 120, remaining: 20 },
      { id: "annual_total", y: 3, earned: 0, required: 20, remaining: 20 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 20, rows: ["2027: Any subject 16", "Any time: Washington Board-approved ethics 4"] },
  },
  {
    id: "WA-6", state: "WA", title: "First period, licensed mid-2025",
    checks: "Licensed 10/1/2025: the first period runs from the issue date to 12/31/2027 with the full 120, and the partial year 2025 still needs 20 (ACB first-period page). 10 in 2025 → red '10 short'.",
    license: { expiration: "2028-06-30", issued: "2025-10-01" },
    courses: [{ title: "Tax Basics", provider: P, date: "2025-11-01", hours: 10, field: "Taxes" }],
    expect: [
      { id: "total", earned: 10, required: 120, remaining: 110 },
      { id: "annual_total", y: 1, earned: 10, required: 20, remaining: 10, past: true },
    ],
    stillNeeded: { total: 110, rows: ["2026: Any subject 20", "2027: Any subject 20", "Any time: Technical 46", "Any time: Washington Board-approved ethics 4", "Any time: Any subject 20"] },
  },
  {
    id: "WA-7", state: "WA", title: "Courses outside the period",
    checks: "A 2024 course (before the period) and a January 2028 course (after Dec 31, 2027) don't count. Only the 20 hours in 2026 count; 2025 is red 'short'.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Old Tax Course", provider: P, date: "2024-11-01", hours: 40, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2026-02-01", hours: 20, field: "Taxes" },
      { title: "Late Webinar", provider: P, date: "2028-01-10", hours: 8, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 20, required: 120, remaining: 100 },
      { id: "annual_total", y: 1, earned: 0, required: 20, remaining: 20, past: true }, { id: "annual_total", y: 2, earned: 20, required: 20, met: true },
    ],
    stillNeeded: { total: 100, rows: ["2027: Any subject 20", "Any time: Technical 36", "Any time: Washington Board-approved ethics 4", "Any time: Any subject 40"] },
  },
  {
    id: "WA-8", state: "WA", title: "Nano-learning over 12",
    checks: "20 hours of nano-learning (Taxes) — only 12 count (WAC 4-30-134), so 8 come off the total and off Technical. With 40 Taxes in 2025 and the Washington ethics course: 56 of 120, Technical 56 of 60. Further hours must not be nano.",
    license: { expiration: "2028-06-30", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 40, field: "Taxes" },
      { title: "Tax Bites", provider: P, date: "2026-03-01", hours: 20, field: "Taxes", delivery: "Nano Learning" },
      { title: "Washington Ethics and Regulation", provider: P, date: "2026-05-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 56, required: 120, remaining: 64 },
      { id: "technical_total", earned: 56, required: 60, remaining: 4 },
      { id: "nano_max", earned: 20, required: 12, over: 8 },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 64, rows: ["2027: Any course except Nano Learning 20", "Any time: Technical 4", "Any time: Any course except Nano Learning 40"] },
  },
  // ── Connecticut ── CPE year July 1, 2026 – June 30, 2027 (report due Dec 31, 2027): 40 hours, up to 20 carried from
  // 2025–26, 4 ethics every three CPE years (2024–25 to 2026–27), 8 audit/attest/compilation for attest work.
  {
    id: "CT-1", state: "CT", title: "Clean slate",
    checks: "40 hours for 2026–27 and 4 ethics hours across 2024–25 to 2026–27. Nothing carried from 2025–26.",
    license: { expiration: "2027-01-31", issued: "2010-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 40, remaining: 40 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "attest", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 40, rows: ["Any time: Ethics 4", "Any time: Any subject 36"] },
  },
  {
    id: "CT-2", state: "CT", title: "Year done",
    checks: "36 Taxes + 4 Regulatory Ethics in 2026–27: 40 of 40 and ethics met.",
    license: { expiration: "2027-01-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2026-08-01", hours: 36, field: "Taxes" },
      { title: "Ethics for CPAs", provider: P, date: "2026-09-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [{ id: "total", earned: 40, required: 40, met: true }, { id: "ethics", earned: 4, required: 4, met: true }],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "CT-3", state: "CT", title: "Carryover capped at 20",
    checks: "60 hours in 2025–26: 20 over 40, all 20 carry into 2026–27. With 10 this year: 30 of 40.",
    license: { expiration: "2027-01-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Marathon", provider: P, date: "2025-09-01", hours: 60, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2026-08-01", hours: 10, field: "Taxes" },
    ],
    expect: [{ id: "total", earned: 30, required: 40, remaining: 10 }],
    stillNeeded: { total: 10, rows: ["Any time: Ethics 4", "Any time: Any subject 6"] },
  },
  {
    id: "CT-4", state: "CT", title: "Carryover doesn't chain",
    checks: "2024–25: 60 (20 carried into 2025–26). 2025–26: 30 of its own + 20 carried = 50, but only its own hours over 40 carry — none. 10 this year: 10 of 40.",
    license: { expiration: "2027-01-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Marathon", provider: P, date: "2024-09-01", hours: 60, field: "Taxes" },
      { title: "Tax Update", provider: P, date: "2025-09-01", hours: 30, field: "Taxes" },
      { title: "Tax Planning", provider: P, date: "2026-08-01", hours: 10, field: "Taxes" },
    ],
    expect: [{ id: "total", earned: 10, required: 40, remaining: 30 }],
    stillNeeded: { total: 30, rows: ["Any time: Ethics 4", "Any time: Any subject 26"] },
  },
  {
    id: "CT-5", state: "CT", title: "Attest: accounting and carryover don't count",
    checks: "Attest work: 8 of the 40 must have a field of study of Audit, Attest or Compilation, from this year's hours (CT DCP Q&A). 50 Auditing in 2025–26 carries 10 toward the 40 but not toward the 8; 30 Accounting this year doesn't count toward the 8.",
    license: { expiration: "2027-01-31", issued: "2010-05-01", practice: ["attest"] },
    courses: [
      { title: "Audit Update", provider: P, date: "2025-09-01", hours: 50, field: "Auditing" },
      { title: "GAAP Update", provider: P, date: "2026-08-01", hours: 30, field: "Accounting" },
    ],
    expect: [
      { id: "total", earned: 40, required: 40, met: true },
      { id: "attest", earned: 0, required: 8, remaining: 8 },
    ],
    stillNeeded: { total: 12, rows: ["Any time: Audit, attest or compilation 8", "Any time: Ethics 4"] },
  },
  {
    id: "CT-6", state: "CT", title: "Attest met with Auditing",
    checks: "8 Auditing + 32 Taxes this year: 40 of 40 and the 8 audit/attest hours met. Ethics still due.",
    license: { expiration: "2027-01-31", issued: "2010-05-01", practice: ["attest"] },
    courses: [
      { title: "Audit Sampling", provider: P, date: "2026-08-01", hours: 8, field: "Auditing" },
      { title: "Tax Update", provider: P, date: "2026-09-01", hours: 32, field: "Taxes" },
    ],
    expect: [{ id: "total", earned: 40, required: 40, met: true }, { id: "attest", earned: 8, required: 8, met: true }],
    stillNeeded: { total: 4, rows: ["Any time: Ethics 4"] },
  },
  {
    id: "CT-7", state: "CT", title: "Ethics window",
    checks: "Ethics in March 2024 is in the 2023–24 CPE year — outside 2024–25 to 2026–27, so ethics is 0 of 4. Ethics in August 2024 (2024–25) would count.",
    license: { expiration: "2027-01-31", issued: "2010-05-01" },
    courses: [
      { title: "Ethics for CPAs", provider: P, date: "2024-03-01", hours: 4, field: "Behavioral Ethics" },
      { title: "Tax Update", provider: P, date: "2026-08-01", hours: 40, field: "Taxes" },
    ],
    expect: [{ id: "total", earned: 40, required: 40, met: true }, { id: "ethics", earned: 0, required: 4, remaining: 4 }],
    stillNeeded: { total: 4, rows: ["Any time: Ethics 4"] },
  },
  {
    id: "CT-8", state: "CT", title: "Licensed this CPE year",
    checks: "Licensed 8/15/2026, in the 2026–27 CPE year: no CPE report for the year the license was first issued (CT DCP Q&A).",
    license: { expiration: "2027-01-31", issued: "2026-08-15" },
    courses: [],
    expect: [{ id: "total", earned: 0, required: 0, met: true }],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "CT-9", state: "CT", title: "Licensed last CPE year",
    checks: "Licensed 4/1/2026 (2025–26): 2026–27 is the first year with 40 hours due. The three-year ethics clock starts then, so ethics isn't due until the end of 2028–29.",
    license: { expiration: "2027-01-31", issued: "2026-04-01" },
    courses: [],
    expect: [{ id: "total", earned: 0, required: 40, remaining: 40 }, { id: "ethics", earned: 0, required: 0, met: true }],
    stillNeeded: { total: 40, rows: ["Any time: Any subject 40"] },
  },
  // ── Arizona ── registration period 4/1/2025 – 3/31/2027: 80 hours; 40 in accounting/auditing/tax/business law/
  // consulting (16 of them accounting/auditing/tax); 16 classroom or live webinar; 4 Arizona ethics; max 20 computer, 4 nano.
  {
    id: "AZ-1", state: "AZ", title: "Clean slate",
    checks: "80 hours: 24 more in the five core subjects beyond the 16 accounting/auditing/tax, 4 ethics, 36 any subject; 16 of them must be classroom or live webinar.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 80, remaining: 80 },
      { id: "live", earned: 0, required: 16, remaining: 16 },
      { id: "core", earned: 0, required: 40, remaining: 40 },
      { id: "aat", earned: 0, required: 16, remaining: 16 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 80, rows: ["Any time: Accounting, auditing, tax, business law or consulting 24", "Any time: Accounting, auditing or tax 16", "Any time: Ethics 4", "Any time: Any subject 36"] },
  },
  {
    id: "AZ-2", state: "AZ", title: "Everything met",
    checks: "30 Taxes live + 20 Accounting self-study + 4 Arizona ethics webinar + 26 Finance self-study = 80; live 34; core 50; ethics met.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2025-06-01", hours: 30, field: "Taxes", delivery: "Group Live" },
      { title: "GAAP Update", provider: P, date: "2025-09-01", hours: 20, field: "Accounting", delivery: "QAS Self Study" },
      { title: "Arizona Ethics and Board Rules", provider: P, date: "2026-02-01", hours: 4, field: "Regulatory Ethics", delivery: "Group Internet Based" },
      { title: "Corporate Finance", provider: P, date: "2026-03-01", hours: 26, field: "Finance", delivery: "QAS Self Study" },
    ],
    expect: [
      { id: "total", earned: 80, required: 80, met: true },
      { id: "live", earned: 34, required: 16, met: true },
      { id: "core", earned: 50, required: 40, met: true },
      { id: "aat", earned: 50, required: 16, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "AZ-3", state: "AZ", title: "Core met without accounting, auditing or tax",
    checks: "40 in consulting and business law meets the 40 but not the 16 accounting/auditing/tax inside it. All self-study, so 16 live hours are still due. 20 more hours: 16 accounting/auditing/tax (live) + 4 ethics.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [
      { title: "Consulting Skills", provider: P, date: "2025-06-01", hours: 30, field: "Management Advisory Services", delivery: "QAS Self Study" },
      { title: "Contracts", provider: P, date: "2025-07-01", hours: 10, field: "Business Law", delivery: "QAS Self Study" },
      { title: "Corporate Finance", provider: P, date: "2025-09-01", hours: 36, field: "Finance", delivery: "QAS Self Study" },
    ],
    expect: [
      { id: "total", earned: 76, required: 80, remaining: 4 },
      { id: "live", earned: 0, required: 16, remaining: 16 },
      { id: "core", earned: 40, required: 40, met: true },
      { id: "aat", earned: 0, required: 16, remaining: 16 },
    ],
    stillNeeded: { total: 20, rows: ["Any time: Accounting, auditing or tax 16", "Any time: Ethics 4"] },
  },
  {
    id: "AZ-4", state: "AZ", title: "Computer courses over 20",
    checks: "30 hours of computer courses (live) — only 20 count, so 10 come off the total and off the live hours. 70 of 80; live 20.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [
      { title: "Excel Mastery", provider: P, date: "2025-06-01", hours: 30, field: "Computer Software and Applications", delivery: "Group Live" },
      { title: "Tax Update", provider: P, date: "2025-09-01", hours: 50, field: "Taxes", delivery: "QAS Self Study" },
    ],
    expect: [
      { id: "total", earned: 70, required: 80, remaining: 10 },
      { id: "computer_max", earned: 30, required: 20, over: 10 },
      { id: "live", earned: 20, required: 16, met: true },
    ],
    stillNeeded: { total: 10, rows: ["Any time: Ethics 4", "Any time: Any subject 6"] },
  },
  {
    id: "AZ-5", state: "AZ", title: "Nano-learning over 4",
    checks: "10 hours of nano-learning (Taxes) — only 4 count (R4-1-453), so 6 come off the total and the core subjects. 44 of 80; further hours must not be nano.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Bites", provider: P, date: "2025-06-01", hours: 10, field: "Taxes", delivery: "Nano Learning" },
      { title: "GAAP Update", provider: P, date: "2025-09-01", hours: 40, field: "Accounting", delivery: "Group Live" },
    ],
    expect: [
      { id: "total", earned: 44, required: 80, remaining: 36 },
      { id: "nano_max", earned: 10, required: 4, over: 6 },
      { id: "core", earned: 44, required: 40, met: true },
    ],
    stillNeeded: { total: 36, rows: ["Any time: Ethics 4", "Any time: Any course except Nano Learning 32"] },
  },
  {
    id: "AZ-6", state: "AZ", title: "Ethics must cover Arizona rules",
    checks: "An AICPA ethics course doesn't meet Arizona's 4 hours, which must include at least 1 hour on Arizona Board statutes and rules. Ethics doesn't count toward the 40.",
    license: { expiration: "2027-03-31", issued: "2010-05-01" },
    courses: [
      { title: "AICPA Ethics", provider: P, date: "2025-06-01", hours: 4, field: "Regulatory Ethics", delivery: "Group Live" },
      { title: "Tax Update", provider: P, date: "2025-09-01", hours: 40, field: "Taxes", delivery: "Group Live" },
    ],
    expect: [
      { id: "total", earned: 44, required: 80, remaining: 36 },
      { id: "core", earned: 40, required: 40, met: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 36, rows: ["Any time: Ethics 4", "Any time: Any subject 32"] },
  },
  {
    id: "AZ-7", state: "AZ", title: "Short first period (proration)",
    checks: "Licensed 2/15/2026, period ends 3/31/2027: 5 quarters (part quarters rounded up) of 8, so 50 hours, 25 core, 10 accounting/auditing/tax, 10 live. Ethics stays 4; the computer and nano maximums aren't prorated.",
    license: { expiration: "2027-03-31", issued: "2026-02-15" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 50, remaining: 50 },
      { id: "live", earned: 0, required: 10, remaining: 10 },
      { id: "core", earned: 0, required: 25, remaining: 25 },
      { id: "aat", earned: 0, required: 10, remaining: 10 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "computer_max", earned: 0, required: 20 },
      { id: "nano_max", earned: 0, required: 4 },
    ],
    stillNeeded: { total: 50, rows: ["Any time: Accounting, auditing, tax, business law or consulting 15", "Any time: Accounting, auditing or tax 10", "Any time: Ethics 4", "Any time: Any subject 21"] },
  },
  // ── New Jersey ── triennial period 1/1/2024 – 12/31/2026: 120 credits, 20 each year, 60 technical,
  // 24 accounting/auditing in public practice, the 4-credit NJ Law & Ethics course.
  {
    id: "NJ-1", state: "NJ", title: "Clean slate",
    checks: "2024 and 2025 have ended with 0 — red 'short'. 120 total, 60 technical (the NJ Law & Ethics course counts inside it), 2026 needs 20.",
    license: { expiration: "2026-12-31", issued: "2010-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 120, remaining: 120 },
      { id: "annual_total", y: 1, earned: 0, required: 20, remaining: 20, past: true },
      { id: "annual_total", y: 2, earned: 0, required: 20, remaining: 20, past: true },
      { id: "annual_total", y: 3, earned: 0, required: 20, remaining: 20 },
      { id: "technical", earned: 0, required: 60, remaining: 60 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "aa", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 120, rows: ["2026: Any subject 20", "Any time: Technical subjects 56", "Any time: New Jersey Law & Ethics 4", "Any time: Any subject 40"] },
  },
  {
    id: "NJ-2", state: "NJ", title: "Everything met",
    checks: "40 each year, all technical, with the NJ Law & Ethics course in 2026.",
    license: { expiration: "2026-12-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2024-03-01", hours: 40, field: "Taxes" },
      { title: "Audit Update", provider: P, date: "2025-03-01", hours: 40, field: "Auditing" },
      { title: "GAAP Update", provider: P, date: "2026-03-01", hours: 36, field: "Accounting" },
      { title: "New Jersey Law and Ethics", provider: P, date: "2026-05-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 120, required: 120, met: true },
      { id: "technical", earned: 120, required: 60, met: true },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 0, rows: [] },
  },
  {
    id: "NJ-3", state: "NJ", title: "Mostly non-technical",
    checks: "80 non-technical + 10 Taxes = 90 of 120, but only 10 technical. 50 more technical are needed (more than the 30 left on the total), 4 of them the NJ Law & Ethics course.",
    license: { expiration: "2026-12-31", issued: "2010-05-01" },
    courses: [
      { title: "Leadership Summit", provider: P, date: "2024-03-01", hours: 40, field: "Personal Development" },
      { title: "Business Writing", provider: P, date: "2025-03-01", hours: 40, field: "Communications and Marketing" },
      { title: "Tax Update", provider: P, date: "2026-03-01", hours: 10, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 90, required: 120, remaining: 30 },
      { id: "technical", earned: 10, required: 60, remaining: 50 },
    ],
    stillNeeded: { total: 50, rows: ["Any time: Technical subjects 46", "Any time: New Jersey Law & Ethics 4"] },
  },
  {
    id: "NJ-4", state: "NJ", title: "Public practice A&A",
    checks: "In public practice: 24 in accounting or auditing (review and compilation count). 60 Taxes + 10 Auditing: A&A 10 of 24.",
    license: { expiration: "2026-12-31", issued: "2010-05-01", practice: ["public_practice"] },
    courses: [
      { title: "Tax Update", provider: P, date: "2024-03-01", hours: 30, field: "Taxes" },
      { title: "Tax Planning", provider: P, date: "2025-03-01", hours: 30, field: "Taxes" },
      { title: "Audit Update", provider: P, date: "2026-03-01", hours: 10, field: "Auditing" },
    ],
    expect: [
      { id: "total", earned: 70, required: 120, remaining: 50 },
      { id: "aa", earned: 10, required: 24, remaining: 14 },
    ],
    stillNeeded: { total: 50, rows: ["2026: Any subject 10", "Any time: Accounting & auditing 14", "Any time: New Jersey Law & Ethics 4", "Any time: Any subject 22"] },
  },
  {
    id: "NJ-5", state: "NJ", title: "A short year",
    checks: "2024 ended with 10 — red '10 short'. 2025 met. 40 of 120 so far.",
    license: { expiration: "2026-12-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2024-03-01", hours: 10, field: "Taxes" },
      { title: "Tax Planning", provider: P, date: "2025-03-01", hours: 30, field: "Taxes" },
    ],
    expect: [
      { id: "total", earned: 40, required: 120, remaining: 80 },
      { id: "annual_total", y: 1, earned: 10, required: 20, remaining: 10, past: true },
      { id: "technical", earned: 40, required: 60, remaining: 20 },
    ],
    stillNeeded: { total: 80, rows: ["2026: Any subject 20", "Any time: Technical subjects 16", "Any time: New Jersey Law & Ethics 4", "Any time: Any subject 40"] },
  },
  {
    id: "NJ-6", state: "NJ", title: "First renewal",
    checks: "Licensed 4/1/2025: the 120/20/technical requirements don't apply to the first renewal (N.J.A.C. 13:29-6.2), but the NJ Law & Ethics course does (13:29-6.3A).",
    license: { expiration: "2026-12-31", issued: "2025-04-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 0, met: true },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 4, rows: ["Any time: New Jersey Law & Ethics 4"] },
  },
  {
    id: "NJ-7", state: "NJ", title: "Software courses and other ethics",
    checks: "Computer Software and Applications isn't on New Jersey's technical list (Information Technology is), so it's non-technical. An AICPA ethics course is technical but isn't the NJ Law & Ethics course.",
    license: { expiration: "2026-12-31", issued: "2010-05-01" },
    courses: [
      { title: "Excel Mastery", provider: P, date: "2024-03-01", hours: 20, field: "Computer Software and Applications" },
      { title: "Tax Update", provider: P, date: "2025-03-01", hours: 20, field: "Taxes" },
      { title: "AICPA Ethics", provider: P, date: "2026-03-01", hours: 4, field: "Regulatory Ethics" },
    ],
    expect: [
      { id: "total", earned: 44, required: 120, remaining: 76 },
      { id: "technical", earned: 24, required: 60, remaining: 36 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
    ],
    stillNeeded: { total: 76, rows: ["2026: Any subject 16", "Any time: Technical subjects 32", "Any time: New Jersey Law & Ethics 4", "Any time: Any subject 24"] },
  },
  // ── Pennsylvania ── reporting period 1/1/2026 – 12/31/2027: 80 hours, 20 each year, 4 ethics, 24 accounting & attest
  // for attest activity, no more than 40 self-study (nano counts as self-study).
  {
    id: "PA-1", state: "PA", title: "Clean slate",
    checks: "80 hours, 20 in 2026 and 20 in 2027, 4 ethics. No accounting & attest line without attest activity.",
    license: { expiration: "2027-12-31", issued: "2010-05-01" },
    courses: [],
    expect: [
      { id: "total", earned: 0, required: 80, remaining: 80 },
      { id: "annual_total", y: 1, earned: 0, required: 20, remaining: 20 },
      { id: "annual_total", y: 2, earned: 0, required: 20, remaining: 20 },
      { id: "self_study_max", earned: 0, required: 40 },
      { id: "ethics", earned: 0, required: 4, remaining: 4 },
      { id: "aa", earned: 0, required: 0, absent: true },
    ],
    stillNeeded: { total: 80, rows: ["2026: Any subject 20", "2027: Any subject 20", "Any time: Professional ethics 4", "Any time: Any subject 36"] },
  },
  {
    id: "PA-2", state: "PA", title: "Halfway, Behavioral Ethics counts",
    checks: "36 Taxes + 4 Behavioral Ethics, all live, in 2026: 40 of 80, ethics met (\"Ethics subjects\"). 2027 can't be done early — it still needs its own 20.",
    license: { expiration: "2027-12-31", issued: "2010-05-01" },
    courses: [
      { title: "Tax Update", provider: P, date: "2026-03-01", hours: 36, field: "Taxes", delivery: "Group Live" },
      { title: "Ethical Decision Making", provider: P, date: "2026-04-01", hours: 4, field: "Behavioral Ethics", delivery: "Group Live" },
    ],
    expect: [
      { id: "total", earned: 40, required: 80, remaining: 40 },
      { id: "annual_total", y: 1, earned: 40, required: 20, met: true },
      { id: "annual_total", y: 2, earned: 0, required: 20, remaining: 20 },
      { id: "ethics", earned: 4, required: 4, met: true },
    ],
    stillNeeded: { total: 40, rows: ["2027: Any subject 20", "Any time: Any subject 20"] },
  },
  {
    id: "PA-3", state: "PA", title: "Too much self-study",
    checks: "60 hours of self-study — only 40 count, so 20 come off the total. Everything left must not be self-study.",
    license: { expiration: "2027-12-31", issued: "2010-05-01" },
    courses: [{ title: "Tax Library", provider: P, date: "2026-03-01", hours: 60, field: "Taxes", delivery: "QAS Self Study" }],
    expect: [
      { id: "total", earned: 40, required: 80, remaining: 40 },
      { id: "self_study_max", earned: 60, required: 40, over: 20 },
    ],
    stillNeeded: { total: 40, rows: ["2027: Any course except self-study 20", "Any time: Professional ethics 4", "Any time: Any course except self-study 16"] },
  },
  {
    id: "PA-4", state: "PA", title: "Attest: self-study over the cap",
    checks: "Attest activity: 24 accounting & attest. 30 Auditing + 30 Accounting, all self-study: 20 over the cap, and since every self-study hour is A&A, the 20 come off A&A too — 40 of 24, still met.",
    license: { expiration: "2027-12-31", issued: "2010-05-01", practice: ["attest"] },
    courses: [
      { title: "Audit Library", provider: P, date: "2026-03-01", hours: 30, field: "Auditing", delivery: "QAS Self Study" },
      { title: "GAAP Library", provider: P, date: "2026-04-01", hours: 30, field: "Accounting", delivery: "QAS Self Study" },
    ],
    expect: [
      { id: "total", earned: 40, required: 80, remaining: 40 },
      { id: "aa", earned: 40, required: 24, met: true },
    ],
    stillNeeded: { total: 40, rows: ["2027: Any course except self-study 20", "Any time: Professional ethics 4", "Any time: Any course except self-study 16"] },
  },
  {
    id: "PA-5", state: "PA", title: "Mixed self-study: excess comes from the other subject",
    checks: "30 Taxes + 20 Auditing self-study (10 over) + 6 Accounting live, attest activity. The 10 over come out of the Taxes hours, so A&A keeps 26.",
    license: { expiration: "2027-12-31", issued: "2010-05-01", practice: ["attest"] },
    courses: [
      { title: "Tax Library", provider: P, date: "2026-02-01", hours: 30, field: "Taxes", delivery: "QAS Self Study" },
      { title: "Audit Library", provider: P, date: "2026-05-01", hours: 20, field: "Auditing", delivery: "QAS Self Study" },
      { title: "GAAP Update", provider: P, date: "2026-08-01", hours: 6, field: "Accounting", delivery: "Group Internet Based" },
    ],
    expect: [
      { id: "total", earned: 46, required: 80, remaining: 34 },
      { id: "self_study_max", earned: 50, required: 40, over: 10 },
      { id: "aa", earned: 26, required: 24, met: true },
    ],
  },
  {
    id: "PA-6", state: "PA", title: "Passed the exam this period",
    checks: "Exam passed 6/1/2026 (entered as the issue date): exempt from CPE for the 2027 renewal (\"Licensees who passed the exam in 2026 or 2027 are exempt\").",
    license: { expiration: "2027-12-31", issued: "2026-06-01" },
    courses: [],
    expect: [{ id: "total", earned: 0, required: 0, met: true }],
    stillNeeded: { total: 0, rows: [] },
  },
];
